Script started on 2015年03月15日 (週日) 16時36分27秒
]0;F74036035@2015cpp: ~/lab1F74036035@2015cpp:~/lab1$ lsgit clone https://github.com/f74036035/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[10Phttps://github.com/f74036035/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[24Pgit config -lhttps://github.com/f74036035/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[24Pgit config -l[2Pwhoami; pwd
F74036035
/home/F74036035/lab1
]0;F74036035@2015cpp: ~/lab1F74036035@2015cpp:~/lab1$ whoami; pwdls[Kgit clone https://github.com/f74036035/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[10Phttps://github.com/f74036035/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[24Pgit config -l
user.name=f74036035
user.email=f74036035@mail.ncku.edu.tw
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=https://github.com/F74036035/lab1.git
branch.master.remote=origin
branch.master.merge=refs/heads/master
remote.paste.url=https://github.com/f74036035/lab1.git
remote.paste.fetch=+refs/heads/*:refs/remotes/paste/*
remote.remote.url=https://github.com/f74036035/lab1.git
remote.remote.fetch=+refs/heads/*:refs/remotes/remote/*
]0;F74036035@2015cpp: ~/lab1F74036035@2015cpp:~/lab1$ git config -l[2Pwhoami; pwdls[Kgit clone https://github.com/f74036035/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[10Phttps://github.com/f74036035/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cgit clone https://github.com/f74036035/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;F74036035@2015cpp: ~/lab1F74036035@2015cpp:~/lab1$ exit

Script done on 2015年03月15日 (週日) 16時36分41秒
