Script started on 2015年03月15日 (週日) 16時56分06秒
]0;F74036035@2015cpp: ~/lab1F74036035@2015cpp:~/lab1$ cd C:\Users\User\lab1[3PC:\Users\User\lab1[5Pcd /user/userC:\Users\User\lab1[5Pcd /user/user.[K[2Plscd ..[1P..[2Plscd lab1homels[Kcd homels[Kcd homelab1ls[Kcd.. ..[3Plscd ./user/userC:\Users\User\lab1cd C:\Users\User\lab1[Kg++ -o[K[K[K[K[K[K/[K./lab1b
input n = 22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 
]0;F74036035@2015cpp: ~/lab1F74036035@2015cpp:~/lab1$ exit

Script done on 2015年03月15日 (週日) 16時56分33秒
